pyg-team/pyg-lib

.github/workflows/codeql_analysis.yml

Code Scanning needs to be configured in order to properly work for compiled languages, see [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#no-code-found-during-the-build). We are going to postpone this step.

Remove C++ Code Scanning

---

.clang-format
.pre-commit-config.yaml
pyg_lib/csrc/library.cpp
pyg_lib/csrc/library.h

Add pre-commit config. It automatically format existing cpp code.
.clang-format file now uses a simple chromium style.

Clang-format with pre-commit

---

.github/workflows/install.yml
.github/workflows/testing.yml
.gitignore
CMakeLists.txt
pyg_lib/__init__.py
setup.py

Allows `cmake` build via `pip install .`

Python `CMakeExtension`

---

pyg_lib/csrc/random/cpu/randint_engine.h
test/csrc/random/test_randint.cpp

Added `randint` to enable fast random. It can be integrated into random samplers.

`randint` utils for samplers

---

CMakeLists.txt
cmake/test.cmake
pyg_lib/csrc/sampler/cpu/random_walk_kernel.cpp
pyg_lib/csrc/sampler/random_walk.h
test/csrc/random/test_randint.cpp
test/csrc/sampler/test_random_walk.cpp
test/csrc/test_library.cpp

In most C++ code style, we are not recommend to use relative path in include path because it is fragile to refactor and hard to debug when `../../blabla/../../blabla` happens.

explicitly specify where to import headers

---

CHANGELOG.md
benchmark/main.py
pyg_lib/csrc/sampler/cpu/mapper.h
pyg_lib/csrc/sampler/cpu/subgraph_kernel.cpp
pyg_lib/testing.py

I thought `pyg::sampler::Mapper` is a clever way to re-use mapping functionality across several samplers. In addition, I noticed that the usage of `std::unordered_map` slows down `subgraph` creation by a significant factor, so I use a simple heuristic to determine if its usage is actually advantageous.

Benchmark scripts and `pyg::sampler::Mapper`

---

.gitmodules
CHANGELOG.md
CMakeLists.txt
pyg_lib/csrc/sampler/cpu/mapper.h

- Added parallel-hashmap to third_party.
- Replaced std::unordered_map with a faster phmap::flat_hash_map.
Results obtained using [main.py](https://github.com/pyg-team/pyg-lib/blob/master/benchmark/main.py) benchmark:
*speedup = time unordered_map / time phmap

Replace unordered_map with a faster version

---

pyg_lib/csrc/ops/cuda/matmul_kernel.cu
pyg_lib/ops/__init__.py

some of the last minute changes to my last MR broke it. test_ops.py was not passing in master. these changes fix that.
master:
```
Traceback (most recent call last):
File "test/ops/test_ops.py", line 46, in <module>
test_segment_matmul_autograd()
File "test/ops/test_ops.py", line 20, in test_segment_matmul_autograd
out.sum().backward()
File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 399, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
return …
```

Fix broken `pyg_lib.ops` package 

---

CHANGELOG.md
benchmark/sampler/neighbor.py
pyg_lib/testing.py

- Added neighbor sampler benchmark to pyg-lib.
- Benchmark measures performance for the neighbor_sample from pyg-lib as well as neighbor_sample from pytorch_sparse.
- Added argument "return_csc" to withDataset decorator to optionally return matrix in CSC format (for the purpose of pytorch_sparse neighbor sample).

Add neighbor sampler benchmark

---

CHANGELOG.md
pyg_lib/csrc/sampler/cpu/index_tracker.h
pyg_lib/csrc/sampler/cpu/indices_tracker.h
pyg_lib/csrc/sampler/cpu/mapper.h
pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp

Apply usage of indicesTracker mechanism in neighbor sample.
IndicesTracker is replacing the unordered_set usage by using vector<char> indexing or flat_hash_set (base on population size).
Contributors/Kudos: @kgajdamo @OlhaBabicheva

Add `IndexTracker` as faster alternative to `unordered_set`

---

CHANGELOG.md
pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp

Sets a default value of `0` nodes for nodes that occur in `node_types` but not `edge_types` (nodes that do not have any edges).

fix(sampler): default value for `mapper_dict`

---

CHANGELOG.md
CMakeLists.txt

By default, cmake created *.dylib, but python uses *.so. We either need to change cmake to write *.so, or change python to use *.dylib. I couldn't figure out how torch-sparse/scatter solve this problem (they seem to be creating *.so files), but happy to change the approach to align with the other projects, if you know.

Build `*.so` extension on Mac instead of `*.dylib`

---

CHANGELOG.md
pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp
pyg_lib/sampler/__init__.py
test/csrc/sampler/test_neighbor.cpp

As discussed offline, we need to unify the implementation for temporal and non-temporal sampling.
This PR updates the neighbor sampling kernel by deciding the range of sampling based on seed node time. We assume we have sorted each neighborhood by time. This assumption will be guaranteed on pyg side in the follow-up PRs.

Require sorted neighborhoods according to time in temporal sampling

---

CHANGELOG.md
CMakeLists.txt
CONTRIBUTING.md
benchmark/csrc/sampler/mapper.cpp
cmake/benchmark.cmake
setup.py

This PR introduces C++ benchmarking infrastructure ([GoogleBenchmark](https://github.com/google/benchmark)). As `pyg-lib` can be used as a standalone C++ library it makes sense to have micro-benchmarks that would benchmark not only pieces of code with a Python binding. Additionally, an exemplary benchmark was provided for `pyg::sampler::Mapper`.
Output for provided benchmark looks like follows:
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                       Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------- …
```

Introduce cpp micro-benchmarks

---

setup.py

Add `build_type` to have an option for easily choosing the `cmake` build type.
Env variables are the same as `torch`.

[Build] Add build type choosing options

---

pyg_lib/csrc/ops/cuda/matmul_kernel.cu

In benchmarking found that the speedup of granularity 4 is inconsequential, even for shapes that don't require padding
considering the additional complexity  that padding adds and that it will inevitably take time to pad, it seems better to just go back to single granularity.
The reason the https://github.com/pyg-team/pyg-lib/pull/73 had such a speed boost was majority from the realization that the backward pass of other must still be for looped for optimal gpu utlization

Reset `segment_matmul` feature granularity back to `1`

---

pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp
pyg_lib/csrc/sampler/cpu/neighbor_kernel.h

It seems that the PyTorch register / dispatching logic is not fully reliable, which causes problems when depending on `neighbor.h` from external libraries. Until this is resolved in a more principled way, we introduce `neighbor_kernel.h` here for external libraries that wish to depend directly on `*_kernel` implementations, that avoid that logic.

Add `neighbor_kernel.h`, remove anonymous namespace

---

pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp

Currently we cast `count` in sampler from `int64_t`
https://github.com/pyg-team/pyg-lib/blob/9f51c5b514ba47008683aef68f0ca8620e5b07be/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp#L302
to `size_t`
https://github.com/pyg-team/pyg-lib/blob/9f51c5b514ba47008683aef68f0ca8620e5b07be/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp#L114
But it's possible that `count` is equal to `-1`. In this case casting to `size_t` will "overflow" to a very large value (18446744073709551615).
Though now there is not much influence (because the very large number almost means that to sample all) but it will be better to fix that if we want to compute on `count` or check whether `count < 0`
https://github.com/pyg-team/pyg-lib/blob/9f51c5b514ba47008683aef68f0ca8620e5b07be/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp#L1 …

Change the type of `count` in neighbor sampling

---

test/ops/test_matmul.py

```
torch.cat([out.mean() for out in outs]).backward()
->
E           RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
```
it seems right before merging my [last PR](https://github.com/pyg-team/pyg-lib/pull/137) to pyg-lib, a last minute [change broke the part of the test under if REQ_GRAD](https://github.com/pyg-team/pyg-lib/pull/137/commits/6d0e998fada44f98aceebbce6d805a22d92e1883) and the CI system was on an older version of pytorch so that part of the test wasn't run since `REQ_GRAD = torch.__version__ >= 1.14.0`
original working code [here](https://github.com/pyg-team/pyg-lib/blob/b2b8cdf4603de6b086d39348ead3daf97fbcd456/test/ops/test_matmul_ops.py#L57-L60)
altered broken code [here](https://github.com/puririshi98/pyg-lib/blob/6d0e998fada44f98aceebbce6d805a …

fix for failing test

---

CHANGELOG.md
benchmark/sampler/hetero_neighbor.py
benchmark/sampler/neighbor.py

- Enabled for both homo and hetero samplers
- For pyg-lib only
- Added arguments: disjoint, temporal, temporal-strategy
- Timestamps are randomly generated

Enable to benchmark neighbor sampler on temporal graphs

---

CHANGELOG.md
pyg_lib/ops/__init__.py
pyg_lib/ops/scatter_reduce.py
setup.py
test/test_triton.py

triton 2.0 issues:
```
_________________________________ test_triton __________________________________
203    @onlyCUDA
204    @onlyTriton
205    def test_triton():
206        x = torch.rand(100, device='cuda')
207        y = torch.rand(100, device='cuda')
208>       assert torch.allclose(x + y, add(x, y))
209test/test_triton.py:37: 
210_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
211test/test_triton.py:28: in add
212    add_kernel[grid](x, y, out, x.numel(), BLOCK_SIZE=1024)
213_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
214args = (tensor([0.6357, 0.4071, 0.4647, 0.2352, 0.8715, 0.7922, 0.7041, 0.1047, 0.1574,
215        0.3703, 0.3483, 0.2265, 0.943...0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., …
```

triton2 support + torch >= 1.14 gmm bias support

---

.gitignore
CHANGELOG.md
pyg_lib/csrc/config.h
pyg_lib/csrc/ops/cpu/matmul_kernel.cpp

Added several fixes and improvements for `(segment|grouped)_matmul`:
* PyTorch stores shape information in `int64_t` variables, whereas MKL uses regular `int`. This means that tensor size can exceed the maximum value acceptable by MKL - in that case we need to use the ATen execution path.
* `config.h` file was removed and added to the .gitignore list - it is automatically generated during the build from the `config.h.in`.
* grain size in MKL sequential execution path was improved, resulting in an average 53% speedup.

`(segment|grouped)_matmul` improvements

---

CHANGELOG.md
pyg_lib/csrc/ops/cpu/index_sort_kernel.cpp

It appears that `vectorized_copy` was causing memory errors in some workloads. This PR fixes these errors.

Fix `index_sort`

---

.pre-commit-config.yaml
.yamllint.yml

@rusty1s This PR aims to further improve the overall structure of the repository by moving the yamllint configuration within the `pre-commit-config.yaml` file.
The only snippet in which the `.yamllint.yml` file was being used was the pre-commit config file. yamllint [allows to have a custom configuration without a config file](https://yamllint.readthedocs.io/en/stable/configuration.html#custom-configuration-without-a-config-file) by using the `-d` flag. Using this feature, we add a serialized version of the config in the args parameter of the pre-commit config.
Similar to https://github.com/pyg-team/pytorch_geometric/pull/6776

chore: move `yamllint` config to pre-commit config

---

CHANGELOG.md
pyg_lib/csrc/ops/cuda/matmul_kernel.cu
pyg_lib/csrc/ops/cuda/sampled_kernel.cu
pyg_lib/csrc/sampler/cuda/random_walk_kernel.cu

CUTLASS grouped gemm requires copying matrix pointers and layouts to the device memory, which brings significant "launch" overheads, more concretely, 7 pageable H2D copies. This PR sets up the arguments for grouped gemm in a CPU pinned buffer manually and copy it to the device memory at once to reduce such overheads.
Other changes include setting CUDA stream for the grouped gemm, adding proper `C10_CUDA_CHECK` and `C10_CUDA_KERNEL_LAUNCH_CHECK`.
Benchmarking with the following script, this PR reduces the op time from 0.29 ms to 0.05 ms on my desktop (RTX 3090).
```python
import torch
import time
import pyg_lib
def bench_pyg(a, b, seg):
seg = torch.tensor(seg)
pyg_lib.ops.segment_matmul(a, seg, b)
torch.cuda.synchronize()
tic = time.time()
for _ in range(10):
pyg_lib.ops.segment_matmul(a, …
```

[Performance] Improve segment_matmul by reducing launching overheads

---

CHANGELOG.md
pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp

The main roadblocks in the context of sampler parallelization is the mapper and the sampler. However, in the case of hetero sampling, there are separate mappers for each dst node type and separate samplers for each edge type. Therefore, to avoid race condition we can use parallelization per dst node type, i.e. each thread is assigned an edge types with unique dst node type that it is working on.
Example sampling times obtained using  [hetero_neighbor.py](https://github.com/pyg-team/pyg-lib/blob/master/benchmark/sampler/hetero_neighbor.py) benchmark:
Example end-to-end times obtained using [inference_benchmark.py](https://github.com/pyg-team/pytorch_geometric/blob/master/benchmark/inference/inference_benchmark.py):

Hetero neighbor sampler multithreading

---

CMakeLists.txt

PyTorch master has updated to `CXX_STANDARD 17` since 5/19/2023. `pyg-lib` needs to update accordingly to avoid build failure.

Update CXX_STANDARD to 17 to align with PyTorch master

---

CHANGELOG.md
pyg_lib/csrc/ops/cuda/matmul_kernel.cu
pyg_lib/ops/__init__.py
test/ops/test_matmul.py

With recent pytorch updates, our original implementation with list of tensors should work, no need for nested tensors
There are still some cases where the for-loop + linear is faster than heterodictlinear but this varies with number of types and size of tensors, so i will learn another sklearn hueristic for HeteroDictLinear the same way i have done for  [HeteroLinear(segmatmul)](https://github.com/pyg-team/pytorch_geometric/pull/7258)

Drop nested tensor wrapper for `grouped_matmul`

---

pyg_lib/ops/__init__.py
test/ops/test_scatter_reduce.py

`import triton` is too slow, so we don't load `fused_scatter_reduce` on import.

Improve `import pyg_lib` speed

---

CHANGELOG.md
pyg_lib/csrc/ops/cuda/matmul_kernel.cu
setup.cfg

up to 20% speedboost (in the extreme setting) on A5000 which isnt even our best ampere gpu

Updating cutlass to v3.1.0, give easy speedboosts to `HeteroLinear`

---

pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp

This branch contains experiments done for the benchmark of the current bidirectional sampling implementation in PYG vs possible alternatives implemented in pyg-lib. (homo only case considered)
**Uploading with the only goal to make it available for future next steps in this direction. Work in progress**
Bidirectional sampling is implemented in master PYG mainly in files [to_bidirectional.py](https://github.com/pyg-team/pytorch_geometric/blob/8fd53f6b654396d5d5c848933993ad3e1fb32bf6/torch_geometric/sampler/utils.py#L115) and [colesce.py](https://github.com/pyg-team/pytorch_geometric/blob/8fd53f6b654396d5d5c848933993ad3e1fb32bf6/torch_geometric/utils/coalesce.py#L4).
Basically the approach taken there is post-processing, acting after the edges are sampled; it adds reverse edges (in …

Bidirectional sampling benchmark: initial experiments

---

CHANGELOG.md
pyg_lib/csrc/ops/cpu/matmul_kernel.cpp

As a part of our internal process, we are running Coverity scans. The goal of this PR is to fix all issues reported as performance issues.

Fix coverity scan issues

---

.github/workflows/building.yml
.github/workflows/cpp_testing.yml
.github/workflows/documentation.yml
.github/workflows/install.yml
.github/workflows/linting.yml
.github/workflows/nightly.yml
.github/workflows/python_testing.yml

`actions/checkout@v3` is broken, see https://github.com/actions/checkout/issues/1448

Upgrade GitHub Action `checkout` version

---

CHANGELOG.md
benchmark/sampler/hetero_neighbor.py
benchmark/sampler/neighbor.py

Added `--biased` parameter to `neighbor.py` and `hetero_neighbor.py` to run benchmarks for biased sampling.
Output for command python neighbor.py --biased --libraries pyg-lib --write-csv :
Output for command python hetero_neighbor.py --biased --libraries pyg-lib --write-csv :

Benchmarks for biased sampling

---

CHANGELOG.md
pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp

Implemented biased sampling using this algorithm: https://utopia.duth.gr/~pefraimi/research/data/2007EncOfAlg.pdf

Optimization of biased sampling

---

CHANGELOG.md
pyg_lib/csrc/ops/cpu/matmul_kernel.cpp
pyg_lib/testing.py
test/ops/test_matmul.py

This PR covers CPU implementation.

Add support for bfloat16 in `segment_matmul` operation

---

CHANGELOG.md
benchmark/ops/softmax.py
pyg_lib/csrc/ops/cpu/softmax_kernel.cpp
pyg_lib/csrc/ops/softmax.cpp
pyg_lib/csrc/ops/softmax.h
pyg_lib/ops/__init__.py
test/csrc/ops/test_softmax.cpp
test/ops/test_softmax.py

This PR adds forward and backward implementation of sparse softmax operation as defined [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/softmax.py#L9).
In the `pytorch_geometric` implementation we cannot take advantage of model compilation when groups are defined via `ptr`. `softmax_csr` introduced here provides a well-performing kernel for such a scenario.
Performance boost (achieved on 28C, single socket machine):
~7x for forward pass
~8x for backward pass
Additionally, GAT training time was reduced by ~5%.

Add `softmax_csr` implementation

---

pyg_lib/csrc/sampler/cpu/dist_merge_outputs_kernel.cpp
pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp
pyg_lib/csrc/sampler/dist_relabel.cpp
pyg_lib/csrc/sampler/dist_relabel.h
test/csrc/sampler/test_dist_merge_outputs.cpp
test/csrc/sampler/test_dist_relabel.cpp

Due to the fact that the implementation of distributed training for hetero has changed, it is also necessary to change the dist hetero relabel neighborhood function.
Related pytorch_geometric PR: [#8503](https://github.com/pyg-team/pytorch_geometric/pull/8503)
Changes made:
- `num_sampled_neighbors_per_node` dictionary currently store information about the number of sampled neighbors for each layer separately: 
`const c10::Dict<rel_type, std::vector<int64_t>>&num_sampled_neighbors_per_node_dict` ->  `const c10::Dict<rel_type, std::vector<std::vector<int64_t>>>&num_sampled_neighbors_per_node_dict`
- The method of mapping nodes has also been changed. This is now done layer by layer.
- After each layer, the range of src nodes for each edge type for the next layer is calculated and the …

Update hetero dist relabel

---

CHANGELOG.md
pyg_lib/csrc/ops/cuda/matmul_kernel.cu
test/ops/test_matmul.py

For example, if `other[i]` was transposed, a new tensor is created in the loop of `for (size_t i = 0; i < num_matrices; ++i) {`. 
The `data_ptr` of the tensor newly created will be used by a kernel following, but this tensor itself may get released before the kernel launch.

[Grouped Matmul] Fix PyTorch memory leak when tensors are not contiguous

---

pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp

- All seed nodes subgraph ids have their own unique subgraph id regardless of type.
- Additionally, the method of retrieving information about the number of nodes of a given type has been changed.

Increment subgraph id globally for all seed nodes

---

pyg_lib/csrc/ops/autograd/matmul_kernel.cpp
pyg_lib/csrc/ops/autograd/sampled_kernel.cpp
pyg_lib/csrc/ops/autograd/softmax_kernel.cpp

Replaces `Variable` with `Tensor` as per the docs:
> The only reason we are keeping the `Variable` class is backward compatibility with external user’s legacy C++ frontend code. Our intention is to eliminate the `Variable` class in the near future. 
https://pytorch.org/cppdocs/api/typedef_namespacetorch_1_1autograd_1aa5771cd953999c4b07b2a022f9d8f1d0.html

Remove usage of `torch::autograd::Variable`

---

.github/workflows/nightly.yml

This PR limits the number of concurrent nightly jobs to let other repos to use the resource of GitHub-hosted runners. Currently, we have 200 scheduled nightly jobs, and each takes from 3.5 min to 15 min, occupying the max number of concurrent jobs (i.e., 20) across all repos `pyg-team` org:
This should be ok because nightly builds don't need to be avaialble ASAP.

Limit concurrency for nightly jobs

---

pyg_lib/ops/scatter_reduce.py

Fixing a bug introduced in [MR#370](https://github.com/pyg-team/pyg-lib/pull/370/files).
After removing `i` but still using `enumerate`, the `reduce` variable is incorrectly set to (0, **value**) instead of the expected **value**.

[Bug] Fixing bug in `fused_scatter_reduce` function.

---

CHANGELOG.md
CMakeLists.txt

Recent change in PyTorch dropped support to pre-cxx11abi:
https://github.com/pytorch/pytorch/pull/149888 
since `pytorch==2.7` + cuda >= 12.6 will ship w/ cxx11abi, pyg-lib needs to follow PyTorch's ABI 
thanks 🙏  @ptrblck for bringing this change to our attention
fix shamelessly taken from https://github.com/NVIDIA/TensorRT-LLM/blob/57cafe7f9bea5286ada3e08cb0d68c78adaf910d/cpp/CMakeLists.txt#L575

Add CXX11 ABI build support

---

.github/workflows/automerge.yml

Only trigger automerge workflow on opening a PR

---

.pre-commit-config.yaml
pyproject.toml

To supress ~an annoyingly loud warning~ a warning in CI:
```
* Building wheel...
/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
************************************************************************** …
```

Avoid deprecated format in `project.license` field in `pyproject.toml`

---

.pre-commit-config.yaml
pyproject.toml

Due to some build issue in certain versions, this reverts commit 10b2fe1192b16dc73ef557ce518a8560d4dcb722.

Revert "Avoid deprecated format in `project.license` field in `pyproject.toml` (#446)"

---

.github/dependabot.yml

We're using very old versions of GHA actions, e.g., stale bot. Updating them manually is not human work. This bot will make sure they're up to date.

ci: Set up dependabot

---

test/ops/test_index_sort.py
test/ops/test_softmax.py

Skips two test cases due to test case failures due to https://github.com/pytorch/pytorch/issues/130619:
```
__________________________ test_index_sort[device0] ___________________________
device = device(type='cpu')
@pytest.mark.parametrize('device', DEVICES)
def test_index_sort(device):
inputs = torch.randperm(100_000, device=device)
ref_sorted_input, ref_indices = torch.sort(inputs, stable=True)
sorted_input, indices = pyg_lib.ops.index_sort(inputs)
>       assert torch.all(ref_sorted_input == sorted_input)
E       assert tensor(False)
E        +  where tensor(False) = <built-in method all of type object at 0x00007FFFB4FFEE80>(tensor([    0, 11966,  7382,  ..., 24002,  2670, 16435]) == tensor([    0,     1,     2,  ..., 99997, 99998, 99999])
E        +    where <built-in method all of …
```

Skip test cases on CPU Windows due to PyTorch 2.4.0 bug

---

.github/workflows/nightly.yml
.github/workflows/nightly_legacy.yml
CHANGELOG.md

Part of #457, https://github.com/pyg-team/pytorch_geometric/issues/10398.
* Triggered at https://github.com/pyg-team/pyg-lib/actions?query=branch%3Aaki%2Fcuda-nightly+event%3Aworkflow_dispatch.
* Built wheels are pushed to https://data.pyg.org/whl/nightly/:
[torch-2.8.0+cpu](https://data.pyg.org/whl/nightly/torch-2.8.0%2Bcpu.html)
[torch-2.8.0+cu126](https://data.pyg.org/whl/nightly/torch-2.8.0%2Bcu126.html)
[torch-2.8.0+cu128](https://data.pyg.org/whl/nightly/torch-2.8.0%2Bcu128.html)
[torch-2.8.0+cu129](https://data.pyg.org/whl/nightly/torch-2.8.0%2Bcu129.html)

Start pushing manylinux wheels built with CUDA

---

.github/workflows/_upload_index.yml

Addresses:
```
Invalid workflow file: .github/workflows/_upload_index.yml#L1
(Line: 16, Col: 15): Unexpected value 'choice', (Line: 17, Col: 9): Unexpected value 'options', (Line: 32, Col: 14): Unexpected value ''
```

ci: Don't use unsupported `type: choice` in `workflow_call`
